const { chromium }=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs=require('fs'),assert=require('assert/strict');
(async()=>{const browser=await chromium.launch({...(process.env.CHROME_PATH ? {executablePath:process.env.CHROME_PATH} : {}),headless:true});try{
const page=await browser.newPage();await page.route('https://rollrune.top/**',r=>r.fulfill({contentType:'text/html',body:'<main><header>RollRune Wiki</header><div style="display:flex"><aside style="width:160px">百科目录</aside><section style="min-width:0;flex:1;overflow:auto;height:95vh"><div>原生内容</div></section></div></main>'}));await page.goto('https://rollrune.top/wiki');const source=fs.readFileSync('rollrune-helper.user.js','utf8').split('// === RollRune Wiki Search ===')[1];await page.addScriptTag({content:source});await page.locator('#rr-wiki-launch').click();
const panel=page.locator('#rr-wiki-search');const field=id=>panel.locator(`[data-field="${id}"]`);const count=()=>panel.locator('[aria-live]').textContent();await page.waitForFunction(()=>document.querySelector('#rr-wiki-search [aria-live]').textContent.startsWith('265 /'));
await field('kind').selectOption('暗金');await page.waitForFunction(()=>document.querySelector('#rr-wiki-search [aria-live]').textContent.startsWith('102 /'));
await field('kind').selectOption('被动');await page.waitForFunction(()=>document.querySelector('#rr-wiki-search [aria-live]').textContent.startsWith('163 /'));
await field('query').fill('毒素 伤害');await page.waitForTimeout(200);const all=parseInt(await count());assert.ok(all>0);await field('mode').selectOption('any');await page.waitForTimeout(100);assert.ok(parseInt(await count())>=all);
await field('scope').selectOption('name');await field('query').fill('<img src=x onerror=alert(1)>');await page.waitForTimeout(200);assert.ok((await count()).startsWith('0 /'));assert.equal(await panel.locator('img').count(),0);
await panel.getByRole('button',{name:'重置',exact:true}).click();await panel.getByRole('button',{name:'下一页',exact:true}).click();assert.ok((await count()).includes('第 2 /'));
await page.screenshot({path:'tests/wiki-desktop.png'});await page.setViewportSize({width:390,height:844});await page.addStyleTag({content:'aside{display:none}'});const rect=await panel.boundingBox();assert.ok(rect.x>=0&&rect.x+rect.width<=390);await page.screenshot({path:'tests/wiki-mobile.png'});
await page.keyboard.press('Escape');assert.equal(await panel.isVisible(),false);assert.equal(await page.locator('[data-rr-wiki-active]').count(),0);await page.goto('https://rollrune.top/wiki/uniques');await page.addScriptTag({content:source});await page.waitForFunction(()=>document.querySelector('#rr-wiki-search [aria-live]')?.textContent.startsWith('102 /'));assert.equal(await page.locator('[role=dialog]').count(),0);assert.equal(await page.locator('#rr-wiki-launch').count(),1);
console.log('PASS: 265 entries, 102/163 categories, AND/OR, literal input, pagination, mobile width and Escape.');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
